# Аэропорты все по всему миру
## координаты, все данные по ним, высота высокогорные международные аэропорты

In [32]:
import numpy as np
import pandas as pd
airports = pd.read_csv('C:/Users/student/Desktop/airports.csv',names = ['Airport ID','Name','City','Country','IATA','ICAO','Latitude','Longitude','Altitude','Timezone','DST','Tz_database_time_zone','Type','Source'])
airports.head()
routes = pd.read_csv('C:/Users/student/Desktop/routes.csv',names = ['Airline','Airport ID','Source airport','Source airport ID','Destination airport','Destination airport ID','Codeshare','Stops','Equipment'])
routes.head()
airlines = pd.read_csv('C:/Users/student/Desktop/airlines.csv',names = ['Airline ID','Name','Alias','IATA','ICAO','Callsign','Country','Active'])
routes

,Airline,Airport ID,Source airport,Source airport ID,Destination airport,Destination airport ID,Codeshare,Stops,Equipment
0,2B,410,AER,2965,KZN,2990,NaN,0,CR2
1,2B,410,ASF,2966,KZN,2990,NaN,0,CR2
2,2B,410,ASF,2966,MRV,2962,NaN,0,CR2
3,2B,410,CEK,2968,KZN,2990,NaN,0,CR2
4,2B,410,CEK,2968,OVB,4078,NaN,0,CR2
5,2B,410,DME,4029,KZN,2990,NaN,0,CR2
6,2B,410,DME,4029,NBC,6969,NaN,0,CR2
7,2B,410,DME,4029,TGK,\N,NaN,0,CR2
8,2B,410,DME,4029,UUA,6160,NaN,0,CR2
9,2B,410,EGO,6156,KGD,2952,NaN,0,CR2
10,2B,410,EGO,6156,KZN,2990,NaN,0,CR2
11,2B,410,GYD,2922,NBC,6969,NaN,0,CR2
12,2B,410,KGD,2952,EGO,6156,NaN,0,CR2
13,2B,410,KZN,2990,AER,2965,NaN,0,CR2
14,2B,410,KZN,2990,ASF,2966,NaN,0,CR2
15,2B,410,KZN,2990,CEK,2968,NaN,0,CR2
16,2B,410,KZN,2990,DME,4029,NaN,0,CR2
17,2B,410,KZN,2990,EGO,6156,NaN,0,CR2
18,2B,410,KZN,2990,LED,2948,NaN,0,CR2
19,2B,410,KZN,2990,SVX,2975,NaN,0,CR2
20,2B,410,LED,2948,KZN,2990,NaN,0,CR2
21,2B,410,LED,2948,NBC,6969,NaN,0,CR2
22,2B,410,LED,2948,UUA,6160,NaN,0,CR2
23,2B,410,MRV,2962,ASF,2966,NaN,0,CR2
24,2B,410,NBC,6969,DME,4029,NaN,0,CR2
25,2B,410,NBC,6969,GYD,2922,NaN,0,CR2
26,2B,410,NBC,6969,LED,2948,NaN,0,CR2
27,2B,410,NBC,6969,SVX,2975,NaN,0,CR2
28,2B,410,NJC,2972,SVX,2975,NaN,0,CR2
29,2B,410,NJC,2972,UUA,6160,NaN,0,CR2
...,...,...,...,...,...,...,...,...,...
67633,ZL,4178,SYD,3361,ABX,3333,NaN,0,SF3
67634,ZL,4178,SYD,3361,ARM,4062,NaN,0,SF3
67635,ZL,4178,SYD,3361,BHQ,6241,NaN,0,SF3
67636,ZL,4178,SYD,3361,BHS,6249,NaN,0,SF3
67637,ZL,4178,SYD,3361,BNK,4291,NaN,0,SF3
67638,ZL,4178,SYD,3361,DBO,3358,NaN,0,SF3
67639,ZL,4178,SYD,3361,GFF,6271,NaN,0,SF3
67640,ZL,4178,SYD,3361,LSY,6287,NaN,0,SF3
67641,ZL,4178,SYD,3361,MIM,6294,NaN,0,SF3
67642,ZL,4178,SYD,3361,MQL,6298,NaN,0,SF3
67643,ZL,4178,SYD,3361,MYA,6302,NaN,0,SF3
67644,ZL,4178,SYD,3361,NRA,6307,NaN,0,SF3
67645,ZL,4178,SYD,3361,NTL,4320,NaN,0,SF3
67646,ZL,4178,SYD,3361,OAG,6793,NaN,0,SF3
67647,ZL,4178,SYD,3361,PKE,6317,NaN,0,SF3
67648,ZL,4178,SYD,3361,TRO,6794,NaN,0,SF3
67649,ZL,4178,SYD,3361,WGA,3363,NaN,0,SF3
67650,ZL,4178,TRO,6794,GFN,6792,NaN,0,SF3
67651,ZL,4178,TRO,6794,SYD,3361,NaN,0,SF3
67652,ZL,4178,TSV,3330,ISA,3324,NaN,0,SF3
67653,ZL,4178,TSV,3330,WIN,6337,NaN,0,SF3
67654,ZL,4178,WGA,3363,MEL,3339,NaN,0,SF3
67655,ZL,4178,WGA,3363,SYD,3361,NaN,0,SF3
67656,ZL,4178,WIN,6337,LRE,6289,NaN,0,SF3
67657,ZL,4178,WIN,6337,TSV,3330,NaN,0,SF3
67658,ZL,4178,WYA,6334,ADL,3341,NaN,0,SF3
67659,ZM,19016,DME,4029,FRU,2912,NaN,0,734
67660,ZM,19016,FRU,2912,DME,4029,NaN,0,734
67661,ZM,19016,FRU,2912,OSS,2913,NaN,0,734
67662,ZM,19016,OSS,2913,FRU,2912,NaN,0,734

In [31]:
airlines

,Airline ID,Name,Alias,IATA,ICAO,Callsign,Country,Active
0,-1,Unknown,\N,-,NaN,\N,\N,Y
1,1,Private flight,\N,-,NaN,NaN,NaN,Y
2,2,135 Airways,\N,NaN,GNL,GENERAL,United States,N
3,3,1Time Airline,\N,1T,RNX,NEXTIME,South Africa,Y
4,4,2 Sqn No 1 Elementary Flying Training School,\N,NaN,WYT,NaN,United Kingdom,N
5,5,213 Flight Unit,\N,NaN,TFU,NaN,Russia,N
6,6,223 Flight Unit State Airline,\N,NaN,CHD,CHKALOVSK-AVIA,Russia,N
7,7,224th Flight Unit,\N,NaN,TTF,CARGO UNIT,Russia,N
8,8,247 Jet Ltd,\N,NaN,TWF,CLOUD RUNNER,United Kingdom,N
9,9,3D Aviation,\N,NaN,SEC,SECUREX,United States,N
10,10,40-Mile Air,\N,Q5,MLA,MILE-AIR,United States,Y
11,11,4D Air,\N,NaN,QRT,QUARTET,Thailand,N
12,12,611897 Alberta Limited,\N,NaN,THD,DONUT,Canada,N
13,13,Ansett Australia,\N,AN,AAA,ANSETT,Australia,Y
14,14,Abacus International,\N,1B,NaN,NaN,Singapore,Y
15,15,Abelag Aviation,\N,W9,AAB,ABG,Belgium,N
16,16,Army Air Corps,\N,NaN,AAC,ARMYAIR,United Kingdom,N
17,17,Aero Aviation Centre Ltd.,\N,NaN,AAD,SUNRISE,Canada,N
18,18,Aero Servicios Ejecutivos Internacionales,\N,NaN,SII,ASEISA,Mexico,N
19,19,Aero Biniza,\N,NaN,BZS,BINIZA,Mexico,N
20,20,Aero Albatros,\N,NaN,ABM,ALBATROS ESPANA,Spain,N
21,21,Aigle Azur,\N,ZI,AAF,AIGLE AZUR,France,Y
22,22,Aloha Airlines,\N,AQ,AAH,ALOHA,United States,Y
23,23,Alaska Island Air,\N,NaN,AAK,ALASKA ISLAND,United States,N
24,24,American Airlines,\N,AA,AAL,AMERICAN,United States,Y
25,25,Aviation Management Corporation,\N,NaN,AAM,AM CORP,United States,N
26,26,Atlantis Airlines (USA),\N,NaN,AAO,ATLANTIS AIR,United States,N
27,27,Aerovista Airlines,\N,NaN,AAP,AEROVISTA GROUP,United Arab Emirates,N
28,28,Asiana Airlines,\N,OZ,AAR,ASIANA,Republic of Korea,Y
29,29,Askari Aviation,\N,4K,AAS,AL-AAS,Pakistan,Y
...,...,...,...,...,...,...,...,...
6132,20827,Fly France,Fly France,FF,FRF,NaN,France,Y
6133,20875,Jota Aviation,NaN,NaN,ENZ,ENZO,United Kingdom,Y
6134,20881,Europe Jet,Europe Jet,EX,EU9,NaN,France,Y
6135,20923,COBALT,COBALT,NaN,FCB,COBALT,Cyprus,Y
6136,20931,Southern Airways Express,Sun Air Express,NaN,LTD,LIGHTSPEED,United States,Y
6137,20961,Deutsche Luftverkehrsgesellschaft (DLT),NaN,DW,DWD,NaN,Germany,N
6138,20962,Orenburzhie,NaN,NaN,ORG,NaN,Russia,Y
6139,20963,Atlantic Air Cargo,NaN,K3,\N,NaN,United States,N
6140,20976,World Scale Airlines,World Scale,W3,WSS,NaN,United States,Y
6141,20978,All America US,All America US,AG,SSA,NaN,United States,Y
6142,20986,University of Birmingham Air Squadron (RAF),8AEF RAF,NaN,UAY,UAY,United Kingdom,Y
6143,20991,Choice Airways,NaN,NaN,CSX,NaN,United States,Y
6144,20994,Aruba Airlines,NaN,NaN,ARU,NaN,Aruba,Y
6145,20995,BudgetAir,BudgetAir,1K,BG1,NaN,Germany,Y
6146,20996,Dynamic Airways,NaN,NaN,DYA,NaN,United States,Y
6147,21012,Fly One,Fly One,F5,FI5,NaN,Moldova,Y
6148,21021,Nordica,NaN,EE,\N,REVAL,Estonia,Y
6149,21036,Tez Jet Airlines,NaN,NaN,TEZ,NaN,Kyrgyzstan,Y
6150,21043,Kush Air,NaN,NaN,KUH,NaN,South Sudan,Y
6151,21056,Dummy,NaN,0E,\N,NaN,France,N
6152,21124,ViaAir,Charter Air Transport,NaN,SRY,Stingray,United States,Y
6153,21131,All America BOPY,All America BOPY,0P,PYB,BOPY,Paraguay,Y
6154,21179,Thai Vietjet Air,NaN,NaN,TVJ,THAIVIET JET,Thailand,Y
6155,21181,Air Andaman (2Y),NaN,2Y,AOW,AIR ANDAMAN,Thailand,N
6156,21240,TDA Toa Domestic Airlines,TDA,NaN,TDA,Toa Domes,Japan,N
6157,21248,GX Airlines,NaN,NaN,CBG,SPRAY,China,Y
6158,21251,Lynx Aviation (L3/SSX),NaN,NaN,SSX,Shasta,United States,N
6159,21268,Jetgo Australia,NaN,JG,\N,NaN,Australia,Y
6160,21270,Air Carnival,NaN,2S,\N,NaN,India,Y
6161,21317,Svyaz Rossiya,Russian Commuter,7R,SJM,RussianConnecty,Russia,Y

In [33]:
airports[airports['Altitude'] >= 14000]['IATA']

5000    BPX
5819    NGQ
Name: IATA, dtype: object

In [46]:
ports = routes[(routes['Source airport']=='BPX')|(routes['Source airport']=='NGQ')|(routes['Destination airport']=='NGQ')|(routes['Destination airport']=='NGQ')]
ports = np.unique(ports.Airline.values)
ports

array(['CA', 'MU', 'TV', 'ZH'], dtype=object)

In [55]:
np.array([airlines[airlines['IATA']==i]['Name'].values for i in ports ]).T

array([['Air China', 'China Eastern Airlines', 'Virgin Express',
        'Shenzhen Airlines']], dtype=object)