In [1]:
#Отобрать аэропорты Австралии, из которых можно улететь за пределы Австралии
#Посчитать для каждого аэропорта сколько и для какого города я могу улететь
#Найти несовпадения табличек routes и airports
#Упорядочить страны по алфавиту
#Сгруппировать страны по континентам

C:\Users\oabek\Anaconda3\lib\site-packages\ipykernel\parentpoller.py:116: UserWarning: Parent poll failed.  If the frontend dies,
                the kernel may be left running.  Please let us know
                about your system (bitness, Python, etc.) at
                ipython-dev@scipy.org
  ipython-dev@scipy.org""")

In [2]:
import numpy as np
import pandas as pd
from numpy import nan as NA

In [3]:
#Подгружаем данные

airport = pd.read_csv('airports.csv', names = ['ID', 'Name', 'City', 'Country', 'IATA', 'ICAO', 'Latitude', 'Longitude', 'Altitude', 'Timezone', 'DST', 'Tz database time zone', 'Type', 'Source'])
routes = pd.read_csv('routes.csv', names = ['Airline', 'AirlineID', 'SourceAirport', 'Source Airport ID', 'DestinationAirport', 'Destination Airport ID', 'Codeshare', 'Stops', 'Equipment' ])

In [4]:
#Отбираем из таблички airport аэропорт Австралии
#Важно! К Австралии относится не только сам остров Австралия, но и внешние территории, из них на 3 островах есть аэропорты
#В табличке airport в колонке country для них не Australia, а их названия: 
#Norfolk Island, Cocos (Keeling) Islands, Christmas Island
#Поэтому отбираем их тоже

australia = ['Australia', 'Norfolk Island', 'Cocos (Keeling) Islands', 'Christmas Island']
aus_air = airport[airport['Country'].isin(australia)]

In [5]:
#Проверяем есть ли Na в IATA
icao_air = aus_air[aus_air['IATA']=='\\N']
icao_air

,ID,Name,City,Country,IATA,ICAO,Latitude,Longitude,Altitude,Timezone,DST,Tz database time zone,Type,Source
3113,3317,Brisbane Archerfield Airport,Brisbane,Australia,\N,YBAF,-27.570299,153.007996,63,10,O,Australia/Brisbane,airport,OurAirports
3130,3335,RAAF Base East Sale,East Sale,Australia,\N,YMES,-38.098900,147.149002,23,10,O,Australia/Hobart,airport,OurAirports
3135,3340,"RAAF Williams, Point Cook Base",Point Cook,Australia,\N,YMPC,-37.932201,144.753006,14,10,O,Australia/Hobart,airport,OurAirports
3137,3343,RAAF Base Edinburgh,Edinburgh,Australia,\N,YPED,-34.702499,138.621002,67,9.5,O,Australia/Adelaide,airport,OurAirports
3144,3350,Adelaide Parafield Airport,Adelaide,Australia,\N,YPPF,-34.793301,138.632996,57,9.5,O,Australia/Adelaide,airport,OurAirports
3154,3360,RAAF Base Richmond,Richmond,Australia,\N,YSRI,-33.600601,150.781006,67,10,O,Australia/Sydney,airport,OurAirports
5182,6860,Bungle Bungle Airport,Bungle Bungle,Australia,\N,YBUU,-17.545300,128.307007,0,8,U,Australia/Perth,airport,OurAirports
5199,6896,RAAF Base Amberley,Amberley,Australia,\N,YAMB,-27.640600,152.712006,91,10,O,Australia/Brisbane,airport,OurAirports
5201,6898,"RAAF Williams, Laverton Base",Laverton,Australia,\N,YLVT,-37.863602,144.746002,18,10,O,Australia/Hobart,airport,OurAirports
5210,6914,RAAF Base Pearce,Perth,Australia,\N,YPEA,-31.667801,116.014999,149,8,O,Australia/Perth,airport,OurAirports
5211,6915,Bendigo Airport,Bendigo,Australia,\N,YBDG,-36.739399,144.330002,705,10,U,Australia/Hobart,airport,OurAirports
5359,7129,Ballera Airport,Ballera,Australia,\N,YLLE,-27.405633,141.809458,385,10,N,Australia/Brisbane,airport,OurAirports
5360,7130,Gatton Campus Airport,Gatton,Australia,\N,YGAT,-27.560406,152.340460,0,10,N,Australia/Brisbane,airport,OurAirports
5747,7811,Redcliffe Airport,Rothwell,Australia,\N,YRED,-27.206699,153.067993,2,10,U,Australia/Brisbane,airport,OurAirports
5791,7879,Phillip Island Airport,Phillip Island,Australia,\N,YPID,-38.523300,145.326996,13,10,O,Australia/Hobart,airport,OurAirports
6052,8350,Warburton Airport,Warburton Community,Australia,\N,YWBR,-26.128300,126.583000,1500,8,O,Australia/Perth,airport,OurAirports
6053,8351,Cunderdin Airport,Cunderdin,Australia,\N,YCUN,-31.622200,117.217003,705,8,O,Australia/Perth,airport,OurAirports
6055,8353,Forrest Airport,Forrest,Australia,\N,YFRT,-30.838100,128.115005,511,8,O,Australia/Perth,airport,OurAirports
6056,8354,Ballarat Airport,Ballarat,Australia,\N,YBLT,-37.511700,143.791000,1433,10,O,Australia/Hobart,airport,OurAirports
6079,8406,Yarram Airport,Yarram,Australia,\N,YYRM,-38.566700,146.755005,15,10,O,Australia/Hobart,airport,OurAirports
6106,8472,Yalata Mission Airport,Yalata,Australia,\N,YYTA,-31.470600,131.824997,0,9.5,O,Australia/Adelaide,airport,OurAirports
6110,8476,Wyndham Airport,Wyndham,Australia,\N,YWYM,-15.511400,128.153000,14,8,U,Australia/Perth,airport,OurAirports
6217,8696,Beverley Airport,Mine Site,Australia,\N,YBEE,-30.186701,139.557999,116,9.5,O,Australia/Adelaide,airport,OurAirports
6281,8822,Mount Garnet Airport,Mount Garnet,Australia,\N,YMRT,-17.700001,145.149994,657,10,U,Australia/Brisbane,airport,OurAirports
6363,9001,Ivanhoe Airport,Ivanhoe,Australia,\N,YIVO,-32.883301,144.309998,330,10,O,Australia/Sydney,airport,OurAirports
6364,9002,Menindee Airport,Menindee,Australia,\N,YMED,-32.366699,142.404999,0,10,O,Australia/Sydney,airport,OurAirports
6365,9004,Pooncarie Airport,Pooncarie,Australia,\N,YPCE,-33.366699,142.587997,50,10,O,Australia/Sydney,airport,OurAirports
6366,9006,Tilpa Airport,Tilpa,Australia,\N,YTLP,-30.933300,144.417007,0,10,O,Australia/Sydney,airport,OurAirports
6432,9207,Warnervale Airport,Warnervale Airport,Australia,\N,YWVA,-33.240278,151.429722,25,10,U,Australia/Sydney,airport,OurAirports
6520,9542,Coral Bay Airport,Coral Bay,Australia,\N,YCOY,-23.129999,113.777000,5,8,O,Australia/Perth,airport,OurAirports
6569,9818,Lilydale Airport,Lilydale,Australia,\N,YLIL,-37.691700,145.367004,76,10,O,Australia/Hobart,airport,OurAirports
6653,10140,Atherton Airport,Atherton,Australia,\N,YATN,-17.261700,145.514999,2450,10,O,\N,airport,OurAirports
6682,10370,Kadina Airport,Kadina,Australia,\N,YKDI,-33.976700,137.660004,42,9.5,O,\N,airport,OurAirports
6728,11038,Flinders Island Airport,Elliston,Australia,\N,YFLS,-33.730989,134.501000,0,9.5,O,\N,airport,OurAirports
6821,11272,Murray Bridge Airport,Murray Bridge,Australia,\N,YMBD,-35.066700,139.227005,55,10,O,\N,airport,OurAirports
6858,11673,William Creek Airport,William Creek,Australia,\N,YWMC,-28.906700,136.341995,91,9.5,U,\N,airport,OurAirports

In [6]:
#Есть ли IATA не длины 3
aus_air[aus_air['IATA'].str.len()!=3]

,ID,Name,City,Country,IATA,ICAO,Latitude,Longitude,Altitude,Timezone,DST,Tz database time zone,Type,Source
3113,3317,Brisbane Archerfield Airport,Brisbane,Australia,\N,YBAF,-27.570299,153.007996,63,10,O,Australia/Brisbane,airport,OurAirports
3130,3335,RAAF Base East Sale,East Sale,Australia,\N,YMES,-38.098900,147.149002,23,10,O,Australia/Hobart,airport,OurAirports
3135,3340,"RAAF Williams, Point Cook Base",Point Cook,Australia,\N,YMPC,-37.932201,144.753006,14,10,O,Australia/Hobart,airport,OurAirports
3137,3343,RAAF Base Edinburgh,Edinburgh,Australia,\N,YPED,-34.702499,138.621002,67,9.5,O,Australia/Adelaide,airport,OurAirports
3144,3350,Adelaide Parafield Airport,Adelaide,Australia,\N,YPPF,-34.793301,138.632996,57,9.5,O,Australia/Adelaide,airport,OurAirports
3154,3360,RAAF Base Richmond,Richmond,Australia,\N,YSRI,-33.600601,150.781006,67,10,O,Australia/Sydney,airport,OurAirports
5182,6860,Bungle Bungle Airport,Bungle Bungle,Australia,\N,YBUU,-17.545300,128.307007,0,8,U,Australia/Perth,airport,OurAirports
5199,6896,RAAF Base Amberley,Amberley,Australia,\N,YAMB,-27.640600,152.712006,91,10,O,Australia/Brisbane,airport,OurAirports
5201,6898,"RAAF Williams, Laverton Base",Laverton,Australia,\N,YLVT,-37.863602,144.746002,18,10,O,Australia/Hobart,airport,OurAirports
5210,6914,RAAF Base Pearce,Perth,Australia,\N,YPEA,-31.667801,116.014999,149,8,O,Australia/Perth,airport,OurAirports
5211,6915,Bendigo Airport,Bendigo,Australia,\N,YBDG,-36.739399,144.330002,705,10,U,Australia/Hobart,airport,OurAirports
5359,7129,Ballera Airport,Ballera,Australia,\N,YLLE,-27.405633,141.809458,385,10,N,Australia/Brisbane,airport,OurAirports
5360,7130,Gatton Campus Airport,Gatton,Australia,\N,YGAT,-27.560406,152.340460,0,10,N,Australia/Brisbane,airport,OurAirports
5747,7811,Redcliffe Airport,Rothwell,Australia,\N,YRED,-27.206699,153.067993,2,10,U,Australia/Brisbane,airport,OurAirports
5791,7879,Phillip Island Airport,Phillip Island,Australia,\N,YPID,-38.523300,145.326996,13,10,O,Australia/Hobart,airport,OurAirports
6052,8350,Warburton Airport,Warburton Community,Australia,\N,YWBR,-26.128300,126.583000,1500,8,O,Australia/Perth,airport,OurAirports
6053,8351,Cunderdin Airport,Cunderdin,Australia,\N,YCUN,-31.622200,117.217003,705,8,O,Australia/Perth,airport,OurAirports
6055,8353,Forrest Airport,Forrest,Australia,\N,YFRT,-30.838100,128.115005,511,8,O,Australia/Perth,airport,OurAirports
6056,8354,Ballarat Airport,Ballarat,Australia,\N,YBLT,-37.511700,143.791000,1433,10,O,Australia/Hobart,airport,OurAirports
6079,8406,Yarram Airport,Yarram,Australia,\N,YYRM,-38.566700,146.755005,15,10,O,Australia/Hobart,airport,OurAirports
6106,8472,Yalata Mission Airport,Yalata,Australia,\N,YYTA,-31.470600,131.824997,0,9.5,O,Australia/Adelaide,airport,OurAirports
6110,8476,Wyndham Airport,Wyndham,Australia,\N,YWYM,-15.511400,128.153000,14,8,U,Australia/Perth,airport,OurAirports
6217,8696,Beverley Airport,Mine Site,Australia,\N,YBEE,-30.186701,139.557999,116,9.5,O,Australia/Adelaide,airport,OurAirports
6281,8822,Mount Garnet Airport,Mount Garnet,Australia,\N,YMRT,-17.700001,145.149994,657,10,U,Australia/Brisbane,airport,OurAirports
6363,9001,Ivanhoe Airport,Ivanhoe,Australia,\N,YIVO,-32.883301,144.309998,330,10,O,Australia/Sydney,airport,OurAirports
6364,9002,Menindee Airport,Menindee,Australia,\N,YMED,-32.366699,142.404999,0,10,O,Australia/Sydney,airport,OurAirports
6365,9004,Pooncarie Airport,Pooncarie,Australia,\N,YPCE,-33.366699,142.587997,50,10,O,Australia/Sydney,airport,OurAirports
6366,9006,Tilpa Airport,Tilpa,Australia,\N,YTLP,-30.933300,144.417007,0,10,O,Australia/Sydney,airport,OurAirports
6432,9207,Warnervale Airport,Warnervale Airport,Australia,\N,YWVA,-33.240278,151.429722,25,10,U,Australia/Sydney,airport,OurAirports
6520,9542,Coral Bay Airport,Coral Bay,Australia,\N,YCOY,-23.129999,113.777000,5,8,O,Australia/Perth,airport,OurAirports
6569,9818,Lilydale Airport,Lilydale,Australia,\N,YLIL,-37.691700,145.367004,76,10,O,Australia/Hobart,airport,OurAirports
6653,10140,Atherton Airport,Atherton,Australia,\N,YATN,-17.261700,145.514999,2450,10,O,\N,airport,OurAirports
6682,10370,Kadina Airport,Kadina,Australia,\N,YKDI,-33.976700,137.660004,42,9.5,O,\N,airport,OurAirports
6728,11038,Flinders Island Airport,Elliston,Australia,\N,YFLS,-33.730989,134.501000,0,9.5,O,\N,airport,OurAirports
6821,11272,Murray Bridge Airport,Murray Bridge,Australia,\N,YMBD,-35.066700,139.227005,55,10,O,\N,airport,OurAirports
6858,11673,William Creek Airport,William Creek,Australia,\N,YWMC,-28.906700,136.341995,91,9.5,U,\N,airport,OurAirports

In [7]:
#Na есть, но для них для всех есть ID и ICAO, проверим есть ли в routes по ним данные
#Проверить по ID
aus_id = np.array(icao_air['ID'].unique())
aus_id2 = np.array(['{:.0f}'.format(x) for x in aus_id])
routes[routes['Source Airport ID'].isin(aus_id2)]

#С такими ID нет

Empty DataFrame
Columns: [Airline, AirlineID, SourceAirport, Source Airport ID, DestinationAirport, Destination Airport ID, Codeshare, Stops, Equipment]
Index: []

In [8]:
#Проверка по ICAO
#В routes вообще нет  4 буквенных кодов
routes[routes['SourceAirport'].str.len()==4]

Empty DataFrame
Columns: [Airline, AirlineID, SourceAirport, Source Airport ID, DestinationAirport, Destination Airport ID, Codeshare, Stops, Equipment]
Index: []

In [9]:
routes[routes['DestinationAirport'].str.len()==4]

Empty DataFrame
Columns: [Airline, AirlineID, SourceAirport, Source Airport ID, DestinationAirport, Destination Airport ID, Codeshare, Stops, Equipment]
Index: []

In [10]:
#Поэтому можем заменить их на Nan и рабоать дальше без них
aus_air2 = aus_air.replace('\\N',NA)
aus_air2 = aus_air2[aus_air2['IATA'].str.len()==3]
aus_air2.count()

ID                       263
Name                     263
City                     233
Country                  263
IATA                     263
ICAO                     263
Latitude                 263
Longitude                263
Altitude                 263
Timezone                 227
DST                      227
Tz database time zone    214
Type                     263
Source                   263
dtype: int64

In [11]:
#Отберем IATA для австралийских аэропортов, чтобы по ним обобрать маршруты
iata = np.array(aus_air2['IATA'].unique())
iata

array(['ABM', 'ASP', 'BNE', 'OOL', 'CNS', 'CTL', 'ISA', 'MCY', 'MKY',
       'PPP', 'ROK', 'TSV', 'WEI', 'AVV', 'ABX', 'MEB', 'HBA', 'LST',
       'MBW', 'MEL', 'ADL', 'JAD', 'KTA', 'KGI', 'KNX', 'LEA', 'PHE',
       'PER', 'UMR', 'XCH', 'BWU', 'CBR', 'CFS', 'CDU', 'DBO', 'NLK',
       'SYD', 'TMW', 'WGA', 'EMD', 'DRW', 'AYQ', 'KGC', 'HVB', 'ARM',
       'BKQ', 'BDB', 'HIS', 'THG', 'BNK', 'BME', 'NTL', 'ALH', 'GYL',
       'AUU', 'BCI', 'BDD', 'BVI', 'BHQ', 'HTI', 'BEU', 'BRK', 'BUC',
       'GIC', 'OKY', 'BQL', 'BHS', 'BLT', 'CVQ', 'CAZ', 'CPD', 'CNC',
       'CNJ', 'CED', 'CTN', 'CMA', 'CNB', 'CUQ', 'OOM', 'DMD', 'NLF',
       'DPO', 'ELC', 'EPR', 'FLS', 'GET', 'GLT', 'GTE', 'GFF', 'HID',
       'HOK', 'MHU', 'HGD', 'JCK', 'KAX', 'KNS', 'KFG', 'KRB', 'KWM',
       'KUG', 'LNO', 'LEL', 'LDH', 'IRG', 'LSY', 'LHG', 'LRE', 'LER',
       'LVO', 'UBB', 'MKR', 'MIM', 'MGT', 'MNG', 'MCV', 'MQL', 'MMG',
       'MRZ', 'MOV', 'MYA', 'MGB', 'ONG', 'MYI', 'MBH', 'NRA', 'NAA',
       'NTN', 'ZNE', 'OLP', 'PUG', 'PMK', 'PBO', 'CCK', 'GOV', 'PKE',
       'PLO', 'EDR', 'PQQ', 'PTJ', 'ULP', 'RAM', 'RMA', 'SGO', 'MJK',
       'SBR', 'SRN', 'XTG', 'TCA', 'VCD', 'SYU', 'WNR', 'WYA', 'WUN',
       'WOL', 'WIN', 'BWT', 'OKR', 'XMY', 'WME', 'GFN', 'OAG', 'TRO',
       'GUL', 'CES', 'NSO', 'DGE', 'MTL', 'OKB', 'WSY', 'KTR', 'NOA',
       'TWB', 'BWB', 'DRB', 'WGE', 'BRT', 'DKI', 'LZR', 'HLT', 'HCQ',
       'FIZ', 'RVT', 'GEX', 'PEA', 'CDA', 'JAB', 'TEF', 'RMK', 'LGH',
       'RTS', 'XMC', 'YUE', 'GKL', 'RPB', 'IFL', 'MOO', 'ONS', 'TDR',
       'CCL', 'JHQ', 'SHT', 'TEM', 'GAH', 'WIO', 'BEO', 'BMP', 'BQB',
       'IVR', 'GLI', 'KFE', 'COJ', 'BSJ', 'PXH', 'WTB', 'CMQ', 'WMB',
       'RCM', 'DCN', 'BUY', 'CJF', 'BOX', 'PKT', 'GPN', 'HSM', 'SWH',
       'DLK', 'XTO', 'ABH', 'ARY', 'BLN', 'BZD', 'BWQ', 'CVC', 'CWW',
       'CYG', 'CMD', 'DRN', 'DNQ', 'DYA', 'ECH', 'FRB', 'GUH', 'HXX',
       'HTU', 'KRA', 'KPS', 'KGY', 'TGN', 'MRG', 'RPM', 'QRM', 'PPI',
       'SIO', 'SNB', 'SWC', 'TYB', 'TUM', 'WGT', 'WKB', 'QRR', 'SXE',
       'WWY', 'NGA'], dtype=object)

In [12]:
#Отбираем маршруты
aus_abroad = routes[routes['SourceAirport'].isin(iata) & -routes['DestinationAirport'].isin(iata)]

#Коды IATA австралийских аэропортов, из которых можно улететь в другие страны
aus_abroad['SourceAirport'].unique()

array(['DRW', 'PER', 'MEL', 'SYD', 'BNE', 'CNS', 'ADL', 'OOL', 'NLK',
       'PHE'], dtype=object)

In [13]:
#Направления куда летают
aus_abroad['DestinationAirport'].unique()

array(['SIN', 'CTU', 'CKG', 'AKL', 'LAX', 'CHC', 'DFW', 'HNL', 'YVR',
       'DEL', 'HKG', 'AUH', 'BWN', 'TPE', 'PVG', 'PEK', 'POM', 'CAN',
       'KUL', 'DXB', 'WLG', 'BKK', 'ZQN', 'CGK', 'NAN', 'SUV', 'DPS',
       'HIR', 'KIX', 'NRT', 'HKT', 'LOP', 'ICN', 'SCL', 'BKI', 'MRU',
       'NKG', 'SON', 'VLI', 'DUD', 'RAR', 'SFO', 'INU', 'MNL', 'RAB',
       'NOU', 'ZBL', 'DIL', 'SGN', 'JNB', 'DOH', 'GUM', 'APW', 'TBU'],
      dtype=object)

In [14]:
#Количество
len(aus_abroad['DestinationAirport'].unique())

54

In [15]:
air = pd.DataFrame(airport, columns=['IATA','Country'])
air = air.rename(columns = {'IATA': 'DestinationAirport'})
aus = aus_abroad.merge(air, on = 'DestinationAirport', how = 'left')

#Cлили таблички, проверим все ли страны подтянулись
aus['Country'].unique()

array(['Singapore', 'China', 'New Zealand', 'United States', 'Canada',
       'India', 'Hong Kong', 'United Arab Emirates', 'Brunei', 'Taiwan',
       'Papua New Guinea', 'Malaysia', 'Thailand', 'Indonesia', 'Fiji',
       'Solomon Islands', 'Japan', 'South Korea', 'Chile', 'Mauritius',
       'Vanuatu', 'Cook Islands', 'Nauru', 'Philippines', 'New Caledonia',
       nan, 'East Timor', 'Vietnam', 'South Africa', 'Guam', 'Samoa',
       'Tonga'], dtype=object)

In [16]:
aus.count()

Airline                   335
AirlineID                 335
SourceAirport             335
Source Airport ID         335
DestinationAirport        335
Destination Airport ID    335
Codeshare                 119
Stops                     335
Equipment                 335
Country                   332
dtype: int64

In [17]:
aus[aus['Country'].isna()]

,Airline,AirlineID,SourceAirport,Source Airport ID,DestinationAirport,Destination Airport ID,Codeshare,Stops,Equipment,Country
198,QF,4089,BNE,3320,ZBL,\N,Y,0,DH8 DH3,NaN
245,QR,4091,MEL,3339,DOH,11051,NaN,0,77W,NaN
246,QR,4091,PER,3351,DOH,11051,NaN,0,77L,NaN

In [18]:
airport[airport['IATA']=='ZBL']
#В табличке airport нет этого аэропорта
#ZBL это австралийский аэропорт, поэтому проверили летают ли из него в другие страны

Empty DataFrame
Columns: [ID, Name, City, Country, IATA, ICAO, Latitude, Longitude, Altitude, Timezone, DST, Tz database time zone, Type, Source]
Index: []

In [19]:
routes[(routes['SourceAirport']=='ZBL') & -routes['DestinationAirport'].isin(iata)]
#Из него в другие страны не летают, но выкинем его из таблички aus, т.к. в Destination не должны быть австралийские аэропорты

Empty DataFrame
Columns: [Airline, AirlineID, SourceAirport, Source Airport ID, DestinationAirport, Destination Airport ID, Codeshare, Stops, Equipment]
Index: []

In [20]:
airport[airport['IATA']=='DOH']
#Это аэропорт Дохи(Катар) и его тоже не оказалось в табличке airport

Empty DataFrame
Columns: [ID, Name, City, Country, IATA, ICAO, Latitude, Longitude, Altitude, Timezone, DST, Tz database time zone, Type, Source]
Index: []

In [21]:
aus.loc[aus['DestinationAirport'] == 'DOH', 'Country'] = 'Qatar'
aus

,Airline,AirlineID,SourceAirport,Source Airport ID,DestinationAirport,Destination Airport ID,Codeshare,Stops,Equipment,Country
0,3K,3021,DRW,3999,SIN,3316,NaN,0,320,Singapore
1,3K,3021,PER,3351,SIN,3316,NaN,0,320,Singapore
2,3U,4608,MEL,3339,CTU,3395,NaN,0,330,China
3,3U,4608,SYD,3361,CKG,3393,NaN,0,330,China
4,AA,24,BNE,3320,AKL,2006,Y,0,737,New Zealand
5,AA,24,BNE,3320,LAX,3484,Y,0,744,United States
6,AA,24,MEL,3339,LAX,3484,Y,0,380,United States
7,AA,24,SYD,3361,AKL,2006,Y,0,737,New Zealand
8,AA,24,SYD,3361,CHC,2009,Y,0,737,New Zealand
9,AA,24,SYD,3361,DFW,3670,Y,0,744,United States
10,AA,24,SYD,3361,HNL,3728,Y,0,763,United States
11,AA,24,SYD,3361,LAX,3484,Y,0,744 380,United States
12,AB,214,BNE,3320,SIN,3316,Y,0,332,Singapore
13,AC,330,SYD,3361,YVR,156,NaN,0,77L,Canada
14,AI,218,MEL,3339,DEL,3093,NaN,0,788,India
15,AI,218,SYD,3361,DEL,3093,NaN,0,788,India
16,AY,2350,BNE,3320,HKG,3077,NaN,0,333,Hong Kong
17,AY,2350,CNS,3322,HKG,3077,Y,0,333,Hong Kong
18,AY,2350,MEL,3339,HKG,3077,NaN,0,333,Hong Kong
19,AY,2350,SYD,3361,HKG,3077,Y,0,388 744,Hong Kong
20,AZ,596,MEL,3339,AUH,2179,Y,0,77W,United Arab Emirates
21,AZ,596,SYD,3361,AUH,2179,Y,0,77W 346,United Arab Emirates
22,BA,1355,CNS,3322,HKG,3077,Y,0,333,Hong Kong
23,BA,1355,SYD,3361,SIN,3316,NaN,0,777,Singapore
24,BI,4255,MEL,3339,BWN,3272,NaN,0,787,Brunei
25,BR,2091,BNE,3320,TPE,2276,NaN,0,332,Taiwan
26,CA,751,MEL,3339,PVG,3406,NaN,0,330,China
27,CA,751,SYD,3361,PEK,3364,NaN,0,330,China
28,CA,751,SYD,3361,PVG,3406,NaN,0,330,China
29,CG,1308,BNE,3320,POM,5,NaN,0,737,Papua New Guinea
...,...,...,...,...,...,...,...,...,...,...
305,VA,5360,MEL,3339,AKL,2006,Y,0,320 73H 773,New Zealand
306,VA,5360,MEL,3339,AUH,2179,Y,0,77W,United Arab Emirates
307,VA,5360,MEL,3339,CHC,2009,NaN,0,320 73H,New Zealand
308,VA,5360,MEL,3339,DPS,3940,NaN,0,73H,Indonesia
309,VA,5360,MEL,3339,LAX,3484,NaN,0,77W,United States
310,VA,5360,MEL,3339,NAN,1960,Y,0,73H,Fiji
311,VA,5360,MEL,3339,SIN,3316,Y,0,77W 773 388 333,Singapore
312,VA,5360,MEL,3339,WLG,2042,NaN,0,320,New Zealand
313,VA,5360,OOL,3321,AKL,2006,Y,0,73H 320,New Zealand
314,VA,5360,OOL,3321,CHC,2009,NaN,0,320,New Zealand
315,VA,5360,PER,3351,AKL,2006,Y,0,772,New Zealand
316,VA,5360,PER,3351,DPS,3940,Y,0,73H,Indonesia
317,VA,5360,PER,3351,HKT,3179,Y,0,73H,Thailand
318,VA,5360,PER,3351,SIN,3316,NaN,0,772,Singapore
319,VA,5360,PHE,3349,DPS,3940,NaN,0,100,Indonesia
320,VA,5360,SYD,3361,AKL,2006,Y,0,763 73H 320 772,New Zealand
321,VA,5360,SYD,3361,APW,1969,Y,0,73H,Samoa
322,VA,5360,SYD,3361,AUH,2179,NaN,0,77W,United Arab Emirates
323,VA,5360,SYD,3361,CHC,2009,NaN,0,320,New Zealand
324,VA,5360,SYD,3361,DPS,3940,Y,0,73H,Indonesia
325,VA,5360,SYD,3361,HKG,3077,Y,0,346,Hong Kong
326,VA,5360,SYD,3361,HNL,3728,Y,0,332,United States
327,VA,5360,SYD,3361,LAX,3484,NaN,0,77W,United States
328,VA,5360,SYD,3361,NAN,1960,Y,0,73H,Fiji
329,VA,5360,SYD,3361,SIN,3316,Y,0,773 388 772,Singapore
330,VA,5360,SYD,3361,TBU,1963,Y,0,73H,Tonga
331,VA,5360,SYD,3361,WLG,2042,NaN,0,320,New Zealand
332,VN,5309,MEL,3339,SGN,3205,NaN,0,330,Vietnam
333,VN,5309,SYD,3361,SGN,3205,NaN,0,330,Vietnam
334,VS,5347,SYD,3361,HKG,3077,NaN,0,346,Hong Kong

In [22]:
aus_new = aus[aus['DestinationAirport'] != 'ZBL']
aus_new.count()

Airline                   334
AirlineID                 334
SourceAirport             334
Source Airport ID         334
DestinationAirport        334
Destination Airport ID    334
Codeshare                 118
Stops                     334
Equipment                 334
Country                   334
dtype: int64

In [23]:
final = aus_new.pivot_table(values = 'Airline', index=['Country','DestinationAirport'],  columns='SourceAirport', aggfunc='count')
final.sort_index()

SourceAirport                            ADL  BNE  CNS  DRW  MEL  NLK  OOL  \
Country              DestinationAirport
Brunei               BWN                 NaN  NaN  NaN  NaN  1.0  NaN  NaN
Canada               YVR                 NaN  NaN  NaN  NaN  NaN  NaN  NaN
Chile                SCL                 NaN  NaN  NaN  NaN  NaN  NaN  NaN
China                CAN                 NaN  1.0  NaN  NaN  1.0  NaN  NaN
                     CKG                 NaN  NaN  NaN  NaN  NaN  NaN  NaN
                     CTU                 NaN  NaN  NaN  NaN  1.0  NaN  NaN
                     NKG                 NaN  NaN  NaN  NaN  NaN  NaN  NaN
                     PEK                 NaN  NaN  NaN  NaN  NaN  NaN  NaN
                     PVG                 NaN  NaN  NaN  NaN  4.0  NaN  NaN
Cook Islands         RAR                 NaN  NaN  NaN  NaN  NaN  NaN  NaN
East Timor           DIL                 NaN  NaN  NaN  2.0  NaN  NaN  NaN
Fiji                 NAN                 NaN  3.0  NaN  NaN  3.0  NaN  NaN
                     SUV                 NaN  NaN  NaN  NaN  NaN  NaN  NaN
Guam                 GUM                 NaN  NaN  1.0  NaN  NaN  NaN  NaN
Hong Kong            HKG                 1.0  3.0  3.0  NaN  3.0  NaN  NaN
India                DEL                 NaN  NaN  NaN  NaN  1.0  NaN  NaN
Indonesia            CGK                 NaN  NaN  NaN  NaN  1.0  NaN  NaN
                     DPS                 2.0  3.0  NaN  2.0  4.0  NaN  NaN
                     LOP                 NaN  NaN  NaN  NaN  NaN  NaN  NaN
Japan                KIX                 NaN  NaN  3.0  NaN  NaN  NaN  3.0
                     NRT                 NaN  NaN  3.0  NaN  1.0  NaN  3.0
Malaysia             BKI                 NaN  NaN  NaN  NaN  NaN  NaN  NaN
                     KUL                 2.0  1.0  NaN  1.0  4.0  NaN  1.0
Mauritius            MRU                 NaN  NaN  NaN  NaN  NaN  NaN  NaN
Nauru                INU                 NaN  1.0  NaN  NaN  NaN  NaN  NaN
New Caledonia        NOU                 NaN  2.0  NaN  NaN  NaN  NaN  NaN
New Zealand          AKL                 4.0  8.0  3.0  NaN  8.0  1.0  3.0
                     CHC                 NaN  3.0  NaN  NaN  4.0  NaN  3.0
                     DUD                 NaN  2.0  NaN  NaN  NaN  NaN  NaN
                     WLG                 NaN  2.0  NaN  NaN  5.0  NaN  NaN
                     ZQN                 NaN  2.0  NaN  NaN  1.0  NaN  NaN
Papua New Guinea     POM                 NaN  4.0  2.0  NaN  NaN  NaN  NaN
                     RAB                 NaN  NaN  1.0  NaN  NaN  NaN  NaN
Philippines          MNL                 NaN  NaN  NaN  1.0  1.0  NaN  NaN
Qatar                DOH                 NaN  NaN  NaN  NaN  1.0  NaN  NaN
Samoa                APW                 NaN  1.0  NaN  NaN  NaN  NaN  NaN
Singapore            SIN                 3.0  9.0  NaN  4.0  7.0  NaN  1.0
Solomon Islands      HIR                 NaN  2.0  NaN  NaN  NaN  NaN  NaN
South Africa         JNB                 NaN  NaN  NaN  NaN  NaN  NaN  NaN
South Korea          ICN                 NaN  1.0  NaN  NaN  NaN  NaN  NaN
Taiwan               TPE                 NaN  2.0  NaN  NaN  NaN  NaN  NaN
Thailand             BKK                 NaN  2.0  NaN  NaN  3.0  NaN  NaN
                     HKT                 NaN  NaN  NaN  NaN  1.0  NaN  NaN
Tonga                TBU                 NaN  NaN  NaN  NaN  NaN  NaN  NaN
United Arab Emirates AUH                 NaN  NaN  NaN  NaN  3.0  NaN  NaN
                     DXB                 2.0  2.0  NaN  NaN  2.0  NaN  NaN
United States        DFW                 NaN  NaN  NaN  NaN  NaN  NaN  NaN
                     HNL                 NaN  1.0  NaN  NaN  2.0  NaN  NaN
                     LAX                 NaN  4.0  NaN  NaN  4.0  NaN  NaN
                     SFO                 NaN  NaN  NaN  NaN  NaN  NaN  NaN
Vanuatu              SON                 NaN  2.0  NaN  NaN  NaN  NaN  NaN
                     VLI                 NaN  3.0  NaN  NaN  NaN  NaN  NaN
Vietnam              SGN                 NaN  NaN  NaN  NaN  2.0  NaN  NaN

SourceAirport                            PER  PHE   SYD
Country              DestinationAirport
Brunei               BWN                 NaN  NaN   NaN
Canada               YVR                 NaN  NaN   1.0
Chile                SCL                 NaN  NaN   2.0
China                CAN                 1.0  NaN   1.0
                     CKG                 NaN  NaN   1.0
                     CTU                 NaN  NaN   NaN
                     NKG                 NaN  NaN   2.0
                     PEK                 NaN  NaN   1.0
                     PVG                 NaN  NaN   4.0
Cook Islands         RAR                 NaN  NaN   1.0
East Timor           DIL                 NaN  NaN   NaN
Fiji                 NAN                 NaN  NaN   4.0
                     SUV                 NaN  NaN   1.0
Guam                 GUM                 NaN  NaN   NaN
Hong Kong            HKG                 1.0  NaN   5.0
India                DEL                 NaN  NaN   1.0
Indonesia            CGK                 2.0  NaN   2.0
                     DPS                 5.0  1.0   3.0
                     LOP                 1.0  NaN   NaN
Japan                KIX                 NaN  NaN   NaN
                     NRT                 NaN  NaN   2.0
Malaysia             BKI                 1.0  NaN   NaN
                     KUL                 2.0  NaN   2.0
Mauritius            MRU                 1.0  NaN   NaN
Nauru                INU                 NaN  NaN   NaN
New Caledonia        NOU                 NaN  NaN   2.0
New Zealand          AKL                 3.0  NaN  11.0
                     CHC                 NaN  NaN   7.0
                     DUD                 NaN  NaN   NaN
                     WLG                 NaN  NaN   5.0
                     ZQN                 NaN  NaN   3.0
Papua New Guinea     POM                 NaN  NaN   2.0
                     RAB                 NaN  NaN   NaN
Philippines          MNL                 NaN  NaN   2.0
Qatar                DOH                 1.0  NaN   NaN
Samoa                APW                 NaN  NaN   1.0
Singapore            SIN                 9.0  NaN   9.0
Solomon Islands      HIR                 NaN  NaN   NaN
South Africa         JNB                 2.0  NaN   2.0
South Korea          ICN                 NaN  NaN   4.0
Taiwan               TPE                 NaN  NaN   1.0
Thailand             BKK                 2.0  NaN   4.0
                     HKT                 1.0  NaN   1.0
Tonga                TBU                 NaN  NaN   1.0
United Arab Emirates AUH                 NaN  NaN   3.0
                     DXB                 2.0  NaN   2.0
United States        DFW                 NaN  NaN   2.0
                     HNL                 NaN  NaN   5.0
                     LAX                 NaN  NaN   6.0
                     SFO                 NaN  NaN   2.0
Vanuatu              SON                 NaN  NaN   NaN
                     VLI                 NaN  NaN   2.0
Vietnam              SGN                 NaN  NaN   2.0

In [24]:
#Объеденим по континентам, сначала посмотрим какой список стран
aus_new['Country'].unique()

array(['Singapore', 'China', 'New Zealand', 'United States', 'Canada',
       'India', 'Hong Kong', 'United Arab Emirates', 'Brunei', 'Taiwan',
       'Papua New Guinea', 'Malaysia', 'Thailand', 'Indonesia', 'Fiji',
       'Solomon Islands', 'Japan', 'South Korea', 'Chile', 'Mauritius',
       'Vanuatu', 'Cook Islands', 'Nauru', 'Philippines', 'New Caledonia',
       'East Timor', 'Vietnam', 'South Africa', 'Qatar', 'Guam', 'Samoa',
       'Tonga'], dtype=object)

In [25]:
#Соотнесем с континентами
continent = {'Singapore':'Asia', 'China':'Asia', 'New Zealand':'Oceania', 'United States':'North America', 'Canada':'North America',
       'India':'Asia', 'Hong Kong':'Asia', 'United Arab Emirates':'Asia', 'Brunei':'Asia', 'Taiwan':'Asia',
       'Papua New Guinea':'Oceania', 'Malaysia':'Asia', 'Thailand':'Asia', 'Indonesia':'Asia', 'Fiji':'Oceania',
       'Solomon Islands':'Oceania', 'Japan':'Asia', 'South Korea':'Asia', 'Chile':'South America', 'Mauritius':'Africa',
       'Vanuatu':'Oceania', 'Cook Islands':'Oceania', 'Nauru':'Oceania', 'Philippines':'Asia', 'New Caledonia':'Oceania',
       'Qatar':'Asia', 'East Timor':'Asia', 'Vietnam':'Asia', 'South Africa':'Africa', 'Guam':'Oceania', 'Samoa':'Oceania',
       'Tonga':'Oceania'}

In [26]:
aus_new['Continent'] = aus_new['Country'].map(continent)

C:\Users\oabek\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [27]:
aus_new

,Airline,AirlineID,SourceAirport,Source Airport ID,DestinationAirport,Destination Airport ID,Codeshare,Stops,Equipment,Country,Continent
0,3K,3021,DRW,3999,SIN,3316,NaN,0,320,Singapore,Asia
1,3K,3021,PER,3351,SIN,3316,NaN,0,320,Singapore,Asia
2,3U,4608,MEL,3339,CTU,3395,NaN,0,330,China,Asia
3,3U,4608,SYD,3361,CKG,3393,NaN,0,330,China,Asia
4,AA,24,BNE,3320,AKL,2006,Y,0,737,New Zealand,Oceania
5,AA,24,BNE,3320,LAX,3484,Y,0,744,United States,North America
6,AA,24,MEL,3339,LAX,3484,Y,0,380,United States,North America
7,AA,24,SYD,3361,AKL,2006,Y,0,737,New Zealand,Oceania
8,AA,24,SYD,3361,CHC,2009,Y,0,737,New Zealand,Oceania
9,AA,24,SYD,3361,DFW,3670,Y,0,744,United States,North America
10,AA,24,SYD,3361,HNL,3728,Y,0,763,United States,North America
11,AA,24,SYD,3361,LAX,3484,Y,0,744 380,United States,North America
12,AB,214,BNE,3320,SIN,3316,Y,0,332,Singapore,Asia
13,AC,330,SYD,3361,YVR,156,NaN,0,77L,Canada,North America
14,AI,218,MEL,3339,DEL,3093,NaN,0,788,India,Asia
15,AI,218,SYD,3361,DEL,3093,NaN,0,788,India,Asia
16,AY,2350,BNE,3320,HKG,3077,NaN,0,333,Hong Kong,Asia
17,AY,2350,CNS,3322,HKG,3077,Y,0,333,Hong Kong,Asia
18,AY,2350,MEL,3339,HKG,3077,NaN,0,333,Hong Kong,Asia
19,AY,2350,SYD,3361,HKG,3077,Y,0,388 744,Hong Kong,Asia
20,AZ,596,MEL,3339,AUH,2179,Y,0,77W,United Arab Emirates,Asia
21,AZ,596,SYD,3361,AUH,2179,Y,0,77W 346,United Arab Emirates,Asia
22,BA,1355,CNS,3322,HKG,3077,Y,0,333,Hong Kong,Asia
23,BA,1355,SYD,3361,SIN,3316,NaN,0,777,Singapore,Asia
24,BI,4255,MEL,3339,BWN,3272,NaN,0,787,Brunei,Asia
25,BR,2091,BNE,3320,TPE,2276,NaN,0,332,Taiwan,Asia
26,CA,751,MEL,3339,PVG,3406,NaN,0,330,China,Asia
27,CA,751,SYD,3361,PEK,3364,NaN,0,330,China,Asia
28,CA,751,SYD,3361,PVG,3406,NaN,0,330,China,Asia
29,CG,1308,BNE,3320,POM,5,NaN,0,737,Papua New Guinea,Oceania
...,...,...,...,...,...,...,...,...,...,...,...
305,VA,5360,MEL,3339,AKL,2006,Y,0,320 73H 773,New Zealand,Oceania
306,VA,5360,MEL,3339,AUH,2179,Y,0,77W,United Arab Emirates,Asia
307,VA,5360,MEL,3339,CHC,2009,NaN,0,320 73H,New Zealand,Oceania
308,VA,5360,MEL,3339,DPS,3940,NaN,0,73H,Indonesia,Asia
309,VA,5360,MEL,3339,LAX,3484,NaN,0,77W,United States,North America
310,VA,5360,MEL,3339,NAN,1960,Y,0,73H,Fiji,Oceania
311,VA,5360,MEL,3339,SIN,3316,Y,0,77W 773 388 333,Singapore,Asia
312,VA,5360,MEL,3339,WLG,2042,NaN,0,320,New Zealand,Oceania
313,VA,5360,OOL,3321,AKL,2006,Y,0,73H 320,New Zealand,Oceania
314,VA,5360,OOL,3321,CHC,2009,NaN,0,320,New Zealand,Oceania
315,VA,5360,PER,3351,AKL,2006,Y,0,772,New Zealand,Oceania
316,VA,5360,PER,3351,DPS,3940,Y,0,73H,Indonesia,Asia
317,VA,5360,PER,3351,HKT,3179,Y,0,73H,Thailand,Asia
318,VA,5360,PER,3351,SIN,3316,NaN,0,772,Singapore,Asia
319,VA,5360,PHE,3349,DPS,3940,NaN,0,100,Indonesia,Asia
320,VA,5360,SYD,3361,AKL,2006,Y,0,763 73H 320 772,New Zealand,Oceania
321,VA,5360,SYD,3361,APW,1969,Y,0,73H,Samoa,Oceania
322,VA,5360,SYD,3361,AUH,2179,NaN,0,77W,United Arab Emirates,Asia
323,VA,5360,SYD,3361,CHC,2009,NaN,0,320,New Zealand,Oceania
324,VA,5360,SYD,3361,DPS,3940,Y,0,73H,Indonesia,Asia
325,VA,5360,SYD,3361,HKG,3077,Y,0,346,Hong Kong,Asia
326,VA,5360,SYD,3361,HNL,3728,Y,0,332,United States,North America
327,VA,5360,SYD,3361,LAX,3484,NaN,0,77W,United States,North America
328,VA,5360,SYD,3361,NAN,1960,Y,0,73H,Fiji,Oceania
329,VA,5360,SYD,3361,SIN,3316,Y,0,773 388 772,Singapore,Asia
330,VA,5360,SYD,3361,TBU,1963,Y,0,73H,Tonga,Oceania
331,VA,5360,SYD,3361,WLG,2042,NaN,0,320,New Zealand,Oceania
332,VN,5309,MEL,3339,SGN,3205,NaN,0,330,Vietnam,Asia
333,VN,5309,SYD,3361,SGN,3205,NaN,0,330,Vietnam,Asia
334,VS,5347,SYD,3361,HKG,3077,NaN,0,346,Hong Kong,Asia

In [28]:
final2 = aus_new.pivot_table(values = 'Airline', index=['Continent', 'Country','DestinationAirport'],  columns='SourceAirport', aggfunc='count')
final2.sort_index()

SourceAirport                                          ADL  BNE  CNS  DRW  \
Continent     Country              DestinationAirport
Africa        Mauritius            MRU                 NaN  NaN  NaN  NaN
              South Africa         JNB                 NaN  NaN  NaN  NaN
Asia          Brunei               BWN                 NaN  NaN  NaN  NaN
              China                CAN                 NaN  1.0  NaN  NaN
                                   CKG                 NaN  NaN  NaN  NaN
                                   CTU                 NaN  NaN  NaN  NaN
                                   NKG                 NaN  NaN  NaN  NaN
                                   PEK                 NaN  NaN  NaN  NaN
                                   PVG                 NaN  NaN  NaN  NaN
              East Timor           DIL                 NaN  NaN  NaN  2.0
              Hong Kong            HKG                 1.0  3.0  3.0  NaN
              India                DEL                 NaN  NaN  NaN  NaN
              Indonesia            CGK                 NaN  NaN  NaN  NaN
                                   DPS                 2.0  3.0  NaN  2.0
                                   LOP                 NaN  NaN  NaN  NaN
              Japan                KIX                 NaN  NaN  3.0  NaN
                                   NRT                 NaN  NaN  3.0  NaN
              Malaysia             BKI                 NaN  NaN  NaN  NaN
                                   KUL                 2.0  1.0  NaN  1.0
              Philippines          MNL                 NaN  NaN  NaN  1.0
              Qatar                DOH                 NaN  NaN  NaN  NaN
              Singapore            SIN                 3.0  9.0  NaN  4.0
              South Korea          ICN                 NaN  1.0  NaN  NaN
              Taiwan               TPE                 NaN  2.0  NaN  NaN
              Thailand             BKK                 NaN  2.0  NaN  NaN
                                   HKT                 NaN  NaN  NaN  NaN
              United Arab Emirates AUH                 NaN  NaN  NaN  NaN
                                   DXB                 2.0  2.0  NaN  NaN
              Vietnam              SGN                 NaN  NaN  NaN  NaN
North America Canada               YVR                 NaN  NaN  NaN  NaN
              United States        DFW                 NaN  NaN  NaN  NaN
                                   HNL                 NaN  1.0  NaN  NaN
                                   LAX                 NaN  4.0  NaN  NaN
                                   SFO                 NaN  NaN  NaN  NaN
Oceania       Cook Islands         RAR                 NaN  NaN  NaN  NaN
              Fiji                 NAN                 NaN  3.0  NaN  NaN
                                   SUV                 NaN  NaN  NaN  NaN
              Guam                 GUM                 NaN  NaN  1.0  NaN
              Nauru                INU                 NaN  1.0  NaN  NaN
              New Caledonia        NOU                 NaN  2.0  NaN  NaN
              New Zealand          AKL                 4.0  8.0  3.0  NaN
                                   CHC                 NaN  3.0  NaN  NaN
                                   DUD                 NaN  2.0  NaN  NaN
                                   WLG                 NaN  2.0  NaN  NaN
                                   ZQN                 NaN  2.0  NaN  NaN
              Papua New Guinea     POM                 NaN  4.0  2.0  NaN
                                   RAB                 NaN  NaN  1.0  NaN
              Samoa                APW                 NaN  1.0  NaN  NaN
              Solomon Islands      HIR                 NaN  2.0  NaN  NaN
              Tonga                TBU                 NaN  NaN  NaN  NaN
              Vanuatu              SON                 NaN  2.0  NaN  NaN
                                   VLI                 NaN  3.0  NaN  NaN
South America Chile                SCL                 NaN  NaN  NaN  NaN

SourceAirport                                          MEL  NLK  OOL  PER  \
Continent     Country              DestinationAirport
Africa        Mauritius            MRU                 NaN  NaN  NaN  1.0
              South Africa         JNB                 NaN  NaN  NaN  2.0
Asia          Brunei               BWN                 1.0  NaN  NaN  NaN
              China                CAN                 1.0  NaN  NaN  1.0
                                   CKG                 NaN  NaN  NaN  NaN
                                   CTU                 1.0  NaN  NaN  NaN
                                   NKG                 NaN  NaN  NaN  NaN
                                   PEK                 NaN  NaN  NaN  NaN
                                   PVG                 4.0  NaN  NaN  NaN
              East Timor           DIL                 NaN  NaN  NaN  NaN
              Hong Kong            HKG                 3.0  NaN  NaN  1.0
              India                DEL                 1.0  NaN  NaN  NaN
              Indonesia            CGK                 1.0  NaN  NaN  2.0
                                   DPS                 4.0  NaN  NaN  5.0
                                   LOP                 NaN  NaN  NaN  1.0
              Japan                KIX                 NaN  NaN  3.0  NaN
                                   NRT                 1.0  NaN  3.0  NaN
              Malaysia             BKI                 NaN  NaN  NaN  1.0
                                   KUL                 4.0  NaN  1.0  2.0
              Philippines          MNL                 1.0  NaN  NaN  NaN
              Qatar                DOH                 1.0  NaN  NaN  1.0
              Singapore            SIN                 7.0  NaN  1.0  9.0
              South Korea          ICN                 NaN  NaN  NaN  NaN
              Taiwan               TPE                 NaN  NaN  NaN  NaN
              Thailand             BKK                 3.0  NaN  NaN  2.0
                                   HKT                 1.0  NaN  NaN  1.0
              United Arab Emirates AUH                 3.0  NaN  NaN  NaN
                                   DXB                 2.0  NaN  NaN  2.0
              Vietnam              SGN                 2.0  NaN  NaN  NaN
North America Canada               YVR                 NaN  NaN  NaN  NaN
              United States        DFW                 NaN  NaN  NaN  NaN
                                   HNL                 2.0  NaN  NaN  NaN
                                   LAX                 4.0  NaN  NaN  NaN
                                   SFO                 NaN  NaN  NaN  NaN
Oceania       Cook Islands         RAR                 NaN  NaN  NaN  NaN
              Fiji                 NAN                 3.0  NaN  NaN  NaN
                                   SUV                 NaN  NaN  NaN  NaN
              Guam                 GUM                 NaN  NaN  NaN  NaN
              Nauru                INU                 NaN  NaN  NaN  NaN
              New Caledonia        NOU                 NaN  NaN  NaN  NaN
              New Zealand          AKL                 8.0  1.0  3.0  3.0
                                   CHC                 4.0  NaN  3.0  NaN
                                   DUD                 NaN  NaN  NaN  NaN
                                   WLG                 5.0  NaN  NaN  NaN
                                   ZQN                 1.0  NaN  NaN  NaN
              Papua New Guinea     POM                 NaN  NaN  NaN  NaN
                                   RAB                 NaN  NaN  NaN  NaN
              Samoa                APW                 NaN  NaN  NaN  NaN
              Solomon Islands      HIR                 NaN  NaN  NaN  NaN
              Tonga                TBU                 NaN  NaN  NaN  NaN
              Vanuatu              SON                 NaN  NaN  NaN  NaN
                                   VLI                 NaN  NaN  NaN  NaN
South America Chile                SCL                 NaN  NaN  NaN  NaN

SourceAirport                                          PHE   SYD
Continent     Country              DestinationAirport
Africa        Mauritius            MRU                 NaN   NaN
              South Africa         JNB                 NaN   2.0
Asia          Brunei               BWN                 NaN   NaN
              China                CAN                 NaN   1.0
                                   CKG                 NaN   1.0
                                   CTU                 NaN   NaN
                                   NKG                 NaN   2.0
                                   PEK                 NaN   1.0
                                   PVG                 NaN   4.0
              East Timor           DIL                 NaN   NaN
              Hong Kong            HKG                 NaN   5.0
              India                DEL                 NaN   1.0
              Indonesia            CGK                 NaN   2.0
                                   DPS                 1.0   3.0
                                   LOP                 NaN   NaN
              Japan                KIX                 NaN   NaN
                                   NRT                 NaN   2.0
              Malaysia             BKI                 NaN   NaN
                                   KUL                 NaN   2.0
              Philippines          MNL                 NaN   2.0
              Qatar                DOH                 NaN   NaN
              Singapore            SIN                 NaN   9.0
              South Korea          ICN                 NaN   4.0
              Taiwan               TPE                 NaN   1.0
              Thailand             BKK                 NaN   4.0
                                   HKT                 NaN   1.0
              United Arab Emirates AUH                 NaN   3.0
                                   DXB                 NaN   2.0
              Vietnam              SGN                 NaN   2.0
North America Canada               YVR                 NaN   1.0
              United States        DFW                 NaN   2.0
                                   HNL                 NaN   5.0
                                   LAX                 NaN   6.0
                                   SFO                 NaN   2.0
Oceania       Cook Islands         RAR                 NaN   1.0
              Fiji                 NAN                 NaN   4.0
                                   SUV                 NaN   1.0
              Guam                 GUM                 NaN   NaN
              Nauru                INU                 NaN   NaN
              New Caledonia        NOU                 NaN   2.0
              New Zealand          AKL                 NaN  11.0
                                   CHC                 NaN   7.0
                                   DUD                 NaN   NaN
                                   WLG                 NaN   5.0
                                   ZQN                 NaN   3.0
              Papua New Guinea     POM                 NaN   2.0
                                   RAB                 NaN   NaN
              Samoa                APW                 NaN   1.0
              Solomon Islands      HIR                 NaN   NaN
              Tonga                TBU                 NaN   1.0
              Vanuatu              SON                 NaN   NaN
                                   VLI                 NaN   2.0
South America Chile                SCL                 NaN   2.0

In [30]:
airport[airport['IATA']=='DOH']

Empty DataFrame
Columns: [ID, Name, City, Country, IATA, ICAO, Latitude, Longitude, Altitude, Timezone, DST, Tz database time zone, Type, Source]
Index: []